################################################################################
# Configuración del componente afirma-dss-client
################################################################################

################################################################################
# Credenciales de la aplicación (obligatorio)
#
# Si se establecen las propiedades de autenticación mediante BinarySecurityToken
# (certificado) este tipo de autenticación prevalece respecto a la autenticación 
# mediante UsernameToken (usuario / contraseña).
################################################################################
afirma.idapp = ${afirma.idapp}
################################################################################
# BinarySecurityToken
#afirma.authorization.ks.path =
# Tipo del almacen anterior: JKS, PKCS12
#afirma.authorization.ks.type = PKCS12
#afirma.authorization.ks.password = usr
#afirma.authorization.ks.cert.alias = pss
################################################################################
# UsernameToken
afirma.user = ${afirma.user}
afirma.password = ${afirma.password}
################################################################################

################################################################################
# Datos del servidor (obligatorio)
#
# El componente siempre realizará las peticiones al siguiente endpoint:
# https://<afirma_host>/afirmaws/services/<nombre_del_servicio>
################################################################################
afirma.host = ${afirma.host}
################################################################################

################################################################################
# Almacén de certificados de confianza (opcional)
#
# El componente presupone que el almacén de certificados de confianza está
# incluído en el CLASSPATH de la aplicación, por lo que en 'afirma.truststore'
# debe indicarse el nombre del fichero JKS (o bien, la rula relativa al mismo
# dentro del CLASSPATH).
#
# Por ejemplo, una aplicación web (empaquetada en un WAR) cuyo almacén está
# situado en el directorio WEB-INF/classes/almacenconfianza.jks, deberá
# establecer la propiedad afirma.truststore de la siguiente manera:
#
# afirma.truststore = almacenconfianza.jks
#
# También se admite referenciar al almacén de confianza mediante su ruta absoluta.
#
################################################################################
#afirma.truststore = trust.jks
#afirma.truststorePassword = testdes
afirma.truststore = ${afirma.truststore}
afirma.truststorePassword = ${afirma.truststorePassword}
################################################################################

################################################################################
# Autenticación Fachada de Tickets
# 
# Es necesario incluir los siguientes datos si se va a hacer uso de la 
# autenticación mediante la fachada de tickets: servidor de autenticación y urls
# de retorno
################################################################################
# Host del servidor de la fachada SSL de autentiación por tickets 
afirma.tickets.auth.host = ${afirma.tickets.auth.host}
# URL del servlet de retorno definido en el fichero web.xml (este servlet es propio de @firma)
afirma.tickets.url.servlet = ${afirma.tickets.url.servlet}
# URL de vuelta de la aplicación cliente tras finalizar el proceso de autenticación (este Servlet es propio de AGEE)
afirma.tickets.url.app = ${afirma.tickets.url.app}
# URL para hacer la llamada desde local
afirma.tickets.url.auth = ${afirma.tickets.url.auth}
