server:
  port: 8081
  servlet:
    context-path: /ms-svehi-gestion

spring:
  application:
    name: ms-svehi-gestion
  datasource:
    url: jdbc:postgresql://localhost:5432/svehi
    username: svehi_user
    password: svehi_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Configuración de Observabilidad (OTLP)
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,otlp
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
