spring:
  application:
    name: svehi-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/svehidb
    driverClassName: org.postgresql.Driver
    username: svehi
    password: svehi2024
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8080
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  level:
    root: INFO
    es.juntadeandalucia.cpai.svehi: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
